### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jesseday** [adaptdk/adapt-essentials-asset-fields#9]
# Summary

When I installed the app I didn't have a clear sense of what I needed to do in order to be able to use it.  We should document that you have to set it as the homepage.  That can be documented in the readme.

**Comment by whitelisab** [comment]
Hi 👋 I'm with the Integrations Team at Contentful. I just wanted to ➕ this issue, as we just recently had a customer write in to us that they installed this app and they were not clear on what to do next to use the app. Based on the thread we had with the customer, here are a few pieces of info that might be helpful to include in your README:

- Inform users that this app doesn't have an App Configuration Page and doesn't require any configuration after installing
- Provide screenshots/instructions on how to navigate to the Apps tab to use the app in the Page location
- Provide screenshots/instructions on how to set this app to be used in the Home location

Let me know if you have any additional questions, and we will happy to review any updates when you make a PR in our [Marketplace Partner Apps repo](https://github.com/contentful/marketplace-partner-apps).

**Comment by zzzarius** [comment]
Thanks @whitelisab!

Those bullet points are super useful. Will create a PR sortly 👍🏻

**Comment by whitelisab** [comment]
@zzzarius Thanks for the quick follow up on improving your app documentation. I've merged the PR, deployed the changes to your production app, and enabled the app configuration location for your app. Can you please confirm that everything with your app is working as expected? Feel free to open another PR if we need to change anything. Thank you!

**Comment by whitelisab** [comment]
@zzzarius I merged in this fix and deployed to production. I can confirm that I am now seeing the screenshots in the app configuration page.
